name: sliding_puzzle_game
description: A number puzzle game
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shimmer_animation: ^2.1.0+1
  firebase_core: ^1.12.0
  rive: ^0.8.1
  audioplayers: ^0.20.1
  cloud_firestore: ^3.1.8
  mock_data: ^2.0.0
  shared_preferences: ^2.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - images/
    - rive_anim/
  fonts:
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-Regular.ttf
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
    - family: Shizuru
      fonts:
        - asset: fonts/Shizuru-Regular.ttf

